name: Post-Release Tasks

on:
  workflow_call:
    inputs:
      release_tag:
        description: 'The created release tag'
        required: true
        type: string
      release_version:
        description: 'Release type (patch, minor, major, prepatch, preminor, premajor, prerelease)'
        required: true
        type: string
      dry_run:
        description: 'Do not touch or write anything. Show the commands.'
        required: true
        default: false
        type: boolean
    secrets:
      github_token:
        description: 'GitHub token for authentication'
        required: true

jobs:
  post-release:
    runs-on: ubuntu-latest
    steps:
      # Create appropriate milestones based on the release type
      - name: 🏷️ Create GitHub Milestones
        # Skip during dry runs and prereleases
        if: ${{ !inputs.dry_run && !contains(inputs.release_version, 'pre') }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          RELEASE_TYPE: ${{ inputs.release_version }}
        run: |
          echo "::group::Creating GitHub milestones"
          pnpx tsx scripts/create-milestones.ts
          echo "::endgroup::"

      - name: 📝 Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true # Create as draft for manual review
          generate_release_notes: true
          prerelease: ${{ contains(inputs.release_version, 'pre') }}
          repository: webdriverio-community/wdio-electron-service
          tag_name: ${{ inputs.release_tag }}
          token: ${{ secrets.github_token }}
