name: Setup Environment

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git reference to checkout'
        required: true
        type: string
    secrets:
      deploy_key:
        description: 'SSH deploy key for pushing to the repository'
        required: true
    outputs:
      package_version:
        description: 'Current package version'
        value: ${{ jobs.setup.outputs.package_version }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: 👷 Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.deploy_key }}
          ref: ${{ inputs.ref }}
          fetch-depth: 0 # Full history needed for versioning

      - name: 🧰 Setup PNPM package manager
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: 🛠️ Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' # Enable caching for faster builds

      - name: ⚙️ Install Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: 🔧 Configure Git identity
        run: |
          git config --global user.email "bot@webdriver.io"
          git config --global user.name "WebdriverIO Release Bot"

      - name: 📦 Get package version
        id: get-version
        shell: bash
        run: |
          PKG_JSON='packages/wdio-electron-service/package.json'
          VERSION=$(jq -r '.version' ${PKG_JSON})
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Current package version: ${VERSION}"
