name: E2E Tests - Forge

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      node-version:
        required: true
        type: string
jobs:
  e2e:
    name: E2E forge tests (Forge.${{ inputs.node-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        include:
          - os: 'windows-latest'
            type: 'cjs'
          - os: 'windows-latest'
            type: 'esm'
        # app-build-command: ['build']
        # include:
        #   - os: 'macos-latest'
        #     app-build-command: 'build:mac-universal'
        # e2e-scenario: ['builder', 'forge', 'no-binary']
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: ./.github/workflows/actions/setup-workspace
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: wdio-electron-service
          path: .
          filename: wdio-electron-service-build.zip

      - run: sudo sysctl -q -w kernel.apparmor_restrict_unprivileged_userns=0
        # Workaround for linux CI
        # https://github.com/electron/electron/issues/41066
        if: ${{ contains(matrix.os, 'ubuntu') }}

      - run: pnpm run init-forge:package
        shell: bash

      - run: pnpm run init-forge:apps
        shell: bash

      - run: pnpm exec turbo run build --filter=example-forge-${{ !matrix.type && '*' || matrix.type }} --only
        shell: bash

      - run: pnpm exec turbo run init-e2es test:e2e:forge-esm test:e2e:forge-cjs --only --concurrency=1
        shell: bash
        if: ${{ !matrix.type }}
      - run: pnpm exec turbo run init-e2es test:e2e:forge-${{matrix.type}} --only --concurrency=1
        shell: bash
        if: ${{ matrix.type }}

      - name: 🐛 Show logs
        shell: bash
        if: failure()
        run: |
          pnpm run ci:e2e:logs

      - name: 🐛 Upload logs
        uses: ./.github/workflows/actions/upload-archive
        if: failure()
        with:
          name: ${{ matrix.os }}-e2e-forge-logs
          output: ${{ matrix.os }}-e2e-forge-logs.zip
          paths: e2e/*/*.log

      - name: 🐛 Debug Build
        uses: stateful/vscode-server-action@v1.1.0
        if: failure()
        with:
          timeout: '180000'
