name: CI

on:
  push:
  pull_request:

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  build:
    uses: ./.github/workflows/ci-build.yml

  lint:
    needs: [build]
    uses: ./.github/workflows/ci-lint.yml

  unit:
    needs: [build, lint]
    uses: ./.github/workflows/ci-unit.yml

  # e2e-mac:
  #   name: E2E for Mac
  #   needs: [build]
  #   uses: ./.github/workflows/ci-mac.yml
  #   with:
  #     node-version: '20'

  e2e-mac-universal:
    name: E2E for Mac
    needs: [build]
    uses: ./.github/workflows/ci-mac.yml
    with:
      node-version: '20'
      e2e-scenario: '["builder", "forge"]'
      app-build-command: 'build:mac-universal'

  e2e-forge:
    name: E2E for Forge
    needs: [build]
    uses: ./.github/workflows/ci-lnx.yml
    with:
      node-version: '20'

  e2e-builder:
    name: E2E for Builder
    needs: [build]
    uses: ./.github/workflows/ci-win.yml
    with:
      node-version: '20'
      e2e-scenario: 'builder'

  e2e-no-binary:
    name: E2E for No-Binary
    needs: [build, e2e-builder]
    uses: ./.github/workflows/ci-win.yml
    with:
      node-version: '20'
      e2e-scenario: 'no-binary'
