name: CI

on:
  push:
  pull_request:

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - uses: ./.github/workflows/actions/setup-workspace
        with:
          node-version: '20'

      - name: 👷 Build Packages
        run: pnpm run build
        shell: bash

      - name: ⬆️ Upload Build Artifacts
        uses: ./.github/workflows/actions/upload-archive
        with:
          name: wdio-electron-service
          output: wdio-electron-service-build.zip
          paths: packages/*/dist packages/*/cjs
  unit:
    needs: [build]
    uses: ./.github/workflows/ci-unit.yml

  e2e:
    name: E2E Tests
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        node-version: ['20']
        e2e-scenario: ['builder', 'forge', 'no-binary']
    uses: ./.github/workflows/ci-e2e.yml
    with:
      os: ${{ matrix.os }}
      node-version: ${{ matrix.node-version }}
      e2e-scenario: ${{ matrix.e2e-scenario }}

  e2e-mac-universal:
    name: E2E for Mac-Universal
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        node-version: ['20']
        e2e-scenario: ['builder', 'forge']
    uses: ./.github/workflows/ci-e2e.yml
    with:
      os: 'macOS-latest'
      node-version: ${{ matrix.node-version }}
      e2e-scenario: ${{ matrix.e2e-scenario }}
      app-build-command: 'build:mac-universal'
