name: Manual Pre-Release Publish

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch for pre-release'
        required: true
        default: 'feature'
        type: choice
        options:
          - feature
          - main
      prereleaseVersion:
        description: 'The new prerelease version to create.'
        required: true
        default: 'prerelease'
        type: choice
        options:
          - prepatch
          - preminor
          - premajor
          - prerelease
      dryRun:
        description: 'Do not touch or write anything. Show the commands.'
        required: true
        default: false
        type: boolean

jobs:
  # Check if this is the main repository
  check-repo:
    name: Check Repository
    runs-on: ubuntu-latest
    steps:
      - name: Verify Official Repository
        if: ${{ github.repository != 'webdriverio-community/wdio-electron-service' }}
        run: |
          echo "::error::This workflow can only be run in the official repository (webdriverio-community/wdio-electron-service)"
          exit 1

  pre-release:
    name: Pre-release
    needs: [check-repo]
    uses: ./.github/workflows/release-shared.yml
    with:
      branch: ${{ inputs.branch }}
      releaseVersion: ${{ inputs.prereleaseVersion }}
      dryRun: ${{ inputs.dryRun }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}
      deploy-key: ${{ secrets.DEPLOY_KEY }}
