---
name: Manual Release Publish

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main' # Default to main for most common case
        type: choice
        options:
          - main # Current stable
          - feature # Next major development
          - maintenance # LTS/maintenance
      releaseVersion:
        description: 'Release type - patch, minor, or major'
        required: true
        default: 'patch' # Default to patch for most common case
        type: choice
        options: ['patch', 'minor', 'major']
      dryRun:
        description: 'Do not touch or write anything. Show the commands.'
        required: true
        default: false
        type: boolean

jobs:
  # Check if this is the main repository
  check-repo:
    name: Check Repository
    runs-on: ubuntu-latest
    steps:
      - name: Verify Official Repository
        if: ${{ github.repository != 'webdriverio-community/wdio-electron-service' }}
        run: |
          echo "::error::This workflow can only be run in the official repository (webdriverio-community/wdio-electron-service)"
          exit 1

  release:
    name: Release
    needs: [check-repo]
    uses: ./.github/workflows/release-shared.yml
    with:
      branch: ${{ inputs.branch }}
      releaseVersion: ${{ inputs.releaseVersion }}
      dryRun: ${{ inputs.dryRun }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}
      deploy-key: ${{ secrets.DEPLOY_KEY }}
