---
name: Manual Release Publish

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release from'
        required: true
        type: choice
        options:
          - main # Current stable (v8.x)
          - feature/v9 # Next major (v9.0.0-alpha)
          - v7.x # Maintenance
      releaseVersion:
        description: 'Release type - patch, minor, or major'
        required: true
        type: choice
        options: ['patch', 'minor', 'major']
      dryRun:
        description: 'Do not touch or write anything. Show the commands.'
        required: true
        default: false
        type: boolean

jobs:
  release:
    name: Release
    uses: ./.github/workflows/release-shared.yml
    with:
      branch: ${{ inputs.branch }}
      releaseVersion: ${{ inputs.releaseVersion }}
      dryRun: ${{ inputs.dryRun }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}
      deploy-key: ${{ secrets.DEPLOY_KEY }}
